version: '3.0'
services:
  proxy:
    image: nginx:1.15-alpine
    depends_on:
     - scrapy
    ports:
     - "80:80"
    volumes:
     - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
     - ./home/logs/boardfeeds:/home/root/logs/boardfeeds
     - /mnt/boardfeeds:/mnt/boardfeeds
    networks:
      - back

  scrapy:
    build: .
    tty: true
    depends_on:
      - splash
    volumes:
      - ./yavitrina:/scrapy/yavitrina
      - ./home/scrapyd.conf:/etc/scrapyd/scrapyd.conf
      - ./home/scrapyd.conf:/home/root/.scrapyd.conf
      - /home/ubuntu:/home/root
      #- /home/user1:/home/root
      #- /mnt/boardfeeds:/mnt/boardfeeds
    dns: 8.8.8.8
    #restart: always
    networks:
      - back
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "1"

  spiderkeeper:
    build:
      context: ./SpiderKeeper
      dockerfile: Dockerfile
    depends_on:
      - scrapy
      - db
    tty: true
    networks:
      - back
    volumes:
      - ./home:/home/root
      - /home/ubuntu/vitrina.config.ini:/home/root/config.ini
      - /home/ubuntu/logs:/home/root/logs
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "1"

  splash:
    image: scrapinghub/splash
    command: ["splash", "--max-timeout=3600",  "--disable-lua-sandbox"]
    networks:
      - back
    ports:
      - "5023:5023"
      - "8050:8050"
      - "8051:8051"
    dns: 8.8.8.8
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "1"
    restart: unless-stopped

  db:
    image: postgres:12.1
    environment:
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_USER: vitrina
      POSTGRES_DB: vitrina
    volumes:
      - ./docker/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./docker/db/dumps:/dumps
      - ./docker/db/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./docker/db/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./docker/db/pg_ident.conf:/etc/postgresql/pg_ident.conf
      - db-data:/var/lib/postgresql/data
    ports:
      - "65432:5432"
    networks:
      - back
    command: postgres -c config_file=/etc/postgresql/postgresql.conf

networks:
  back:
    driver: bridge

volumes:
  logs: {}
  db-data: {}
