# -*- coding: utf-8 -*-

occupations = [
    "tapissier d'ameublement",
    "charpentier bois poseur",
    "assistant developpement technique semences",
    "scieur bois",
    "monteur de charpentes bois",
    "monteur de meubles",
    "conducteur d'engins agricoles forestiers",
    "menuisier poseur agenceur",
    "charpentier",
    "ouvrier pepinieriste conditionnement",
    "stratifieur usineur finisseur",
    "ebeniste",
    "menuisier fabricant",
    "operateur de scierie",
    "geomaticien",
    "conducteur de broyeur",
    "ouvrier d'exploitation forestiere",
    "technicien ingenieur forestier",
    "conducteur de travaux forestiers",
    "dessinateur d'etudes batiments travaux publics",
    "operateur vernissage",
    "jardinier elagueur",
    "ouvrier pepiniere",
    "encadreur",
    "scieur de tete",
    "tourneur fraiseur",
    "aide menuisier",
    "conducteur d'engins forestiers",
    "technicien d'etudes batiments travaux publics",
    "technicien superieur ingenieur conseil de gestion forestiere travaux sylvicoles",
    "ingenieur forestier",
    "cartographe geomaticien",
    "monteur poseur agencement",
    "ouvrier paysagiste creation plantation",
    "pepinieriste viticole",
    "tourneur commande numerique cn",
    "menuisier agenceur de cuisines de salles de bains",
    "elagueur verts",
    "chef de projet agencement ebenisterie",
    "menuisier poseur de fermetures",
    "menuisier d'agencement",
    "architecte decorateur interieur concepteur espace de vie cuisines",
    "designer",
    "aide charpentier poseur",
    "vernisseur menuisier",
    "conducteur d'engins de debardage",
    "menuisier bois",
    "conducteur operateur de scierie",
    "menuisier ebeniste agenceur",
    "vernisseur laqueur",
    "peintre vernisseur",
    "ebeniste aeronautique",
    "menuisier poseur",
    "ouvrier ebeniste",
    "chef d'equipe elagueur grimpeur bucheron",
    "pilote de scie",
    "finisseur",
    "charpentier atelier",
    "approvisionneur",
    "dessinateur metreur",
    "conducteur de travaux elagage",
    "charpentier menuisier",
    "menuisier plaquiste",
    "pepinieriste",
    "peintre finisseur",
    "tapissier decorateur",
    "economiste de construction",
    "architecte d'interieur",
    "conducteur d ' engins forestiers",
    "tourneur",
    "agenceur d'interieur",
    "ouvrier paysagiste forestier",
    "tonnelier de fabrication",
    "architecte decorateur interieur concepteur espace de vie design",
    "approvisionneur logistique",
    "vernisseur bois",
    "geomaticien charge d'etudes sig",
    "menuisier charpentier",
    "technicien forestier",
    "vernisseur industriel",
    "technicien bureau d'etudes",
    "chauffeur super poids lourd grumier",
    "conducteur d'engins d'exploitation forestiere",
    "tourneur sur bois",
    "charge de projet amenagement territoire",
    "ouvrier forestier polyvalent",
    "menuisier agenceur ebeniste",
    "agent d'horticulture pepinieres oho",
    "metreur second oeuvre",
    "agent de fabrication tonnelier",
    "approvisionneur regional",
    "tonnelier menuisier",
    "projeteur bureau d'etudes",
    "preparateur de commande pepiniere",
    "technicien forestier territorial",
    "ouvrier sylviculteur",
    "ebeniste menuisier",
    "technicien forestier exploitation forestiere approvisionnement bois",
    "technico commercial deviseur",
    "assembleur monteur",
    "menuisier industrie bois",
    "dessinateur bureau d'etudes",
    "menuisier atelier bois",
    "charpentier bois",
    "agent pepinieriste",
    "monteur plv itinerant",
    "grimpeur elagueur",
    "commis de coupe",
    "menuisier",
    "menuisier bois metallier",
    "approvisionneur region",
    "ouvrier sylvicole",
    "technicien bureau d'etude charpente bois",
    "menuisier ebeniste",
    "chef d'equipe elagueur",
    "metreur verificateur",
    "tonnelier",
    "ouvrier paysagiste elagueur",
    "chef d'equipe de travaux forestiers",
    "conducteur d'abatteuses",
    "charge d'etude de prix metreur",
    "approvisionneur surface",
    "ingenieur des techniques forestieres",
    "conducteur de chargeuse porteur forestier",
    "menuisier d'atelier",
    "menuisier poseur atelier",
    "chef d'equipe de scierie",
    "menuisier installateur",
    "ouvrier pepinieriste",
    "aide pepinieriste",
    "sculpteur",
    "monteur",
    "bucheron",
    "menuisier operateur commande numerique",
    "bucheron elagueur",
    "metreur charpente menuiserie bois",
    "approvisionneur magasin",
    "ingenieur technicien forestier",
    "tonnelier reparateur",
    "deviseur",
    "paysagiste elagueur",
    "aide charpentier",
    "charpentier zingueur",
    "ouvrier forestier",
    "metreur",
    "metreur deviseur",
    "ouvrier bois",
    "chef d'equipe charpentier",
    "technicien forestier exploitation forestiere vente de bois",
    "agenceur",
    "acheteur",
    "charpentier poseur",
    "chauffeur grumier",
    "chef d'equipe elagueur bucheron",
    "ebeniste agenceur",
    "monteur agencement",
    "ouvrier de scierie",
    "monteur de maisons ossature bois",
    "elagueur grimpeur",
    "marqueteur",
    "menuisier agenceur",
    "conseiller forestier",
    "assistant de production pepiniere",
    "menuisier poseur agencement",
    "elagueur",
    "monteur de palettes",
    "agent pepinieriste oho",
    "ebeniste monteur meubles",
    "vernisseur",
    "architecte decorateur interieur concepteur espace de vie meubles",
    "parqueteur menuisier",
    "poseur de parquet",
    "ponceur vitrificateur",
    "sylviculteur",
    "mecanicien affuteur",
    "mecanicien d’entretien en exploitation forestiere",
    "constructeur bois",
    "responsable du parc a grumes",
    "responsable de parc a bois",
    "cariste",
    "magasinier",
    "manutentionnaire bois",
    "couvreur charpentier",
    "ingenieur papetier",
    "aide conducteur de machines a papier ou carton",
    "aide secheur en industrie papetiere",
    "Bobineur en industrie papetiere",
    "calandreur en industrie papetiere",
    "conducteur de ligne en industrie papetiere",
    "conducteur de machines a onduler",
    "enrouleur en industrie papetiere",
    "conducteur de machines d'impression",
    "imprimeur",
    "responsable commercial bois",
    "attache commercial bois",
    "technico commercial bois",
    "negociant en bois",
    "vendeur bois",
    "controleur de gestion",
    "comptable",
    "assistant ressources humaines",
    "peintre bois",
    "peinture bois"
]

occupations_old = [
    "ouvrier paysagiste forestier",
    "charpentier",
    "ingenieur forestier",
    "conducteur d 'engins forestiers",
    "deviseur",
    "pepinieriste viticole",
    "geomaticien",
    "ouvrier forestier polyvalent",
    "responsable de scierie",
    "ouvrier paysagiste creation plantation",
    "conducteur operateur de scierie",
    "contremaitre",
    "charge d'etude de prix metreur",
    "tapissier d'ameublement",
    "ouvrier de scierie",
    "technico commercial deviseur",
    "chef d'equipe elagueur bucheron",
    "tourneur commande numerique cn",
    "ouvrier ebeniste",
    "ingenieur papetier",
    "ebeniste agenceur",
    "sculpteur",
    "ouvrier paysagiste elagueur",
    "economiste de construction",
    "tonnelier",
    "agent forestier",
    "elagueur espaces verts",
    "ouvrier pepinieriste conditionnement",
    "assistant de production pepiniere",
    "ebeniste monteur meubles",
    "finisseur / vernisseur",
    "ebeniste",
    "cartographe geomaticien",
    "projeteur bureau d'etudes",
    "grimpeur elagueur",
    "architecte decorateur interieur concepteur espace de vie cuisines",
    "chauffeur super poids lourd grumier",
    "aide pepinieriste",
    "chef d'equipe charpentier",
    "conducteur d'abatteuse",
    "technicien bureau d'etude charpente bois",
    "operateur atelier bois",
    "ebeniste aeronautique",
    "architecte d'interieur",
    "tourneur fraiseur",
    "tourneur",
    "commis de coupe",
    "conducteur de machine onduleuse",
    "jardinier elagueur",
    "agent d'horticulture pepinieres oho",
    "monteur",
    "architecte decorateur interieur concepteur espace de vie meubles",
    "pilote de scie",
    "assistant developpement technique semences",
    "marqueteur",
    "acheteur",
    "geomaticien charge d'etudes sig",
    "elagueur grimpeur",
    "bucheron",
    "chef de projet agencement ebenisterie",
    "ouvrier pepinieriste",
    "designer",
    "conducteur d'engins agricoles forestiers",
    "architecte decorateur interieur concepteur espace de vie design",
    "pepinieriste",
    "encadreur",
    "ouvrier sylvicole",
    "conseiller forestier",
    "technicien forestier",
    "chef d'equipe elagueur grimpeur bucheron",
    "technicien bureau d'etudes",
    "paysagiste elagueur",
    "ouvrier forestier",
    "conducteur d'engins de debardage",
    "conducteur de travaux forestiers",
    "conducteur de travaux elagage",
    "conducteur d'engins d'exploitation forestiere",
    "ouvrier sylviculteur",
    "technicien d'etudes batiments travaux publics",
    "ebeniste menuisier",
    "preparateur de commande pepiniere",
    "chef d'equipe elagueur",
    "menuisier ebeniste",
    "technicien de fabrication de mobilier et de menuiserie",
    "dessinateur bureau d'etudes",
    "agenceur",
    "sculpteur sur bois",
    "scieur de tete",
    "sylviculteur",
    "metreur",
    "ouvrier pepiniere",
    "operateur de scierie",
    "agent pepinieriste",
    "conducteur de chargeur/grue  porteur forestier",
    "chef d'equipe de travaux forestiers",
    "operateur forestier",
    "chauffeur grumier",
    "ouvrier d'exploitation forestiere",
    "charge de projet amenagement territoire",
    "elagueur",
    "tourneur sur bois",
    "scieur bois",
    "menuisier agenceur ebeniste",
    "approvisionneur",
    "agent pepinieriste oho",
    "dessinateur d'etudes batiments travaux publics",
    "menuisier",
    "tapissier decorateur",
    "menuisier ebeniste agenceur",
    "conducteur de broyeur"
]

companies_old = [
    "MEUBLES POUCHAIN","BUT","RADET BERNARD","J.L.J. SARL","L HOTE BRUNO","SOCIETE MARTINELLI",
    "BROUILLARD PHILIPPE","MARCKERT SERGE","BIMBOES DOMINIQUE","ROTT SARL","F AU CARRÉ",
    "SEREMI","MEUBLES GIACOMETTI","SAMM SARL","HOARAU","FERNOLLA","CHERY AGENCEMENT",
    "KARM AGENCEMENT SA","SORNETTE FRÈRES SARL","SARL ANTONY","CUISINA PART","DEITSCH CUISINES",
    "AGENCEMENT MOBILIER BAR RESTAURENT - AMBR","DAVID FONTAINE MENUISERIE","MENUISERIE BARDELANG",
    "GRAFF CONSTRUCTION INOX","B.K.M. AGENCEMENT","R.B.L SARL","MEUBLES VALNET","LES ATELIERS TALENTS HOME",
    "EBENISTERIE D ART LEHMANN","CHENE VERT","POLYSTYL AGENCEMENT","STUTZMANN AGENCEMENT","ADITECH",
    "MEUBLES MULLER","R FLUCKLINGER","EBENISTERIE SELTZ ET FILS","MEUBLES MOUGEOLLE","LE P'TIT MEUBLARD",
    "MEUBLES BORMANN ET CIE","WM88","MANUFACTURE VOSGIENNE DE MEUBLES - MVM","SIMON JEAN-MARIE SARL",
    "HOUOT AGENCEMENT","ADONIS","DECO DESIGN","TITI INTERNATIONAL","MEUBLE DIAMANT","CUISINE PLUS",
    "CUISINES SCHMIDT","MAISON DE LA LITERIE","LITERIE BATTISTINI","SOMNUIT","DEFI CUISINES",
    "BATI LOGIS","HOMEUBLE","STYLES","MEUBLES LINE","USINEST","MEUBLES ANTOINE","SCHMIDT",
    "LA MAISON DE LA LITERIE","CUIR CENTER","FRANCE LITERIE - SOMMEIL ET REVES","ROSEWOOD",
    "CUISINELLA","AGENCIA DESIGN SOTRE 51 - ADS51","BURO CONSEIL LORRAINE","MOBILIER PETITCOLIN",
    "ROMARIC SEGALEN - SIEMATIC","LORRAINE AMENAGEMENTS DE BUREAUX","FRANCE LITERIE","CHATEAU D'AX",
    "BOULEY LITERIE","PLAISIR D' INTERIEUR","OZEO","DIAMOND MEUBLES","EUROPOSE","CUISINE SCHMIDT",
    "MOBALPA","MAISON DEPOT","SOCOO'C","CUISINE SCHMIDT ET  POINT CUISINE","MALITERIE.COM",
    "ORCA FRANCE CUISINES.COM","LORRAINE LITERIE","MONSIEUR MEUBLE","HORIZON CUISNES 57","ESQUISSE CONSULTING & AMENAGEMENT",
    "L'ATELIER CUISINE","PASSION CUISINES 57","DIVOUX BURO","LE BON LIT - L'EXPERT DE VOS NUITS","SOSTRENE GRENE",
    "ALINEA","CINNA","MEUBLES FEUERER","TENDANCES - MADEMOISELLE","LE ROI DU MATELAS","ARREX CUISINES",
    "LA HALLE DU SOMMEIL","KARTELL","NOMEX RAYONNAGES","MATELAS J. HERTZOG","MATAM","KBK CARRELET D OR",
    "AMENAG'MAG","BED & DREAMS LES TECHNICIENS DU SOMMEIL","PREMIER SOMMEIL","MEUBLES DIVO","QUARTZ DESIGN",
    "SOSTERNE GRENE","LITRIMARCHE","BERRINI CUISINES","DESTOCK MOBILIER","ECO CUISINE","REV'ET MEUBLES",
    "M.L. CUISINES","GUILLEMAIN STEPHANE","JYSK","H & H","COCEF CUISINE","ECOCUISINE","BUT COSY","CALLIGARIS",
    "ROCHE BOBOIS","ALSACE LORRAINE POSE ET AGENGEMENT","MOBILIER DE FRANCE","CUISINES AVIVA","KOK","BAZALP GROUP",
    "KUCHEN SPEZIALIST","CUISILINE LIGNE BLEUE","CUISINES KOCHER","MEUBLES DETEMPLE","DIRECT CUISINE","STYLES DE FRANCE",
    "INTERIEUR AMEUBLEMENT","MAINA CUISINES","DM DESIGN","SAMBP","JS CUISINES","TROC.COM","IXINA","LITERIE 10","ALSACE CUISINE",
    "ALTKIRCH MOBILIER","O'MEUBLE","MEUBLES TURQUOISE","MOBALPA MEUBLES COUSOT","CUISINES + BAINS +","MATELAS HERTZOG",
    "INSIDE","SARL FRANZONI VI","CUISINE & CONCEPT","CONFORAMA","SYMPHONIE CUISINES","TITI INTERNATIONALE",
    "QUARTZ","PERENE COLMAR","BLACK BOX","MEUBLES 2.0","PRO-DECO CUISINE","SIGNATURE CUISINES","HABITAT FRANCE",
    "SEXTANT VISUAL SARL","LIGNE ROSET","QUARTZ MOBILIER CONTEMPORAIN","COLMAR CUISINE CREATION - COTE CAVE CONCEPT",
    "MEUBLES KAUTZMANN","LITERIE CONFORT GRAND LITIER","LES GRANDS MAGASINS DE LA LITERIE","LES CUISINES DE JULIA",
    "ECO CUISINE ET BULCINA","GRAPHIC CUISINE","SALONS CENTER - MAISON DE LA LITERIE","TOUSALON-PLACE DE LA LITERIE",
    "IKEA","TOUSALON","SALONS CENTER","AU CARREFOUR DU MEUBLE - LIGNE DESIGN","LA COMPAGNIE DU LIT",
    "LIGNES ROSET MEUBLES TRANI","LA MAISON BLEUE - LITERIE","ATLAS HOME","ATMA CUISINES","ARTHUR BONNET",
    "APID CONCEPT","BLUE MOBLER","MOBEL DISCOUNT","SOCIETE D AMEUBLEMENT CONTEMPORAIN DE LORRAINE",
    "SOCIETE D'AMEUBLEMENT ET DECORATION D'INTERIEUR -SADI-","FLY-LA BOITE A MEUBLES","CUISINES PLUS",
    "GAUTIER","LE PLACARD","LABEL CHAISE","SIEGES BRUNO","AVIVA","DIFFERENCE CUISINES","ESPACE CONCEPTION",
    "PASSION CUISINES ELITE","LA VANNERIE D'AUJOURD'HUI","AMALGAME","GALERIE DECO'ARTS","MEUBLES HORBER SAS",
    "INTERIOR'S","BUREAU VALLEE","BOCONCEPT","LEGRENIER DE PAPY","MAXIMA","ISTIKBAL","MOB'IN STORE",
    "C.T.V. CONCEPT ET DESIGN","CUISINE RAISON","CUISINES SCHMIDT FANY CUISINES","L'UNIVERS DU SOMMEIL",
    "AXEPROD","LE ROIS DU MATELAS","COSY CUISINES","L'ART DE VIVRE BRAYE","CUISINE IXINA","LA HALLE AU SOMMEIL",
    "LA BOUTIQUE DE L'ARTISAN","HOME'S DEPOT","HOME SALONS","MD2","CUISINES ET COINS REPAS","CUISINES & BAINS",
    "GRAND LITIER","WOOD CONSTRUCTION"
]

companies = [
    "gautier france",
    "ricoh industrie france",
    "ds smith packaging velin",
    "editions quo vadis",
    "ober sa",
    "clen",
    "office national des forets",
    "bignon",
    "cetih machecoul (bel'm)",
    "piveteau bois",
    "ekipa",
    "sté ardennaise de menuiserie bois et plastique",
    "arjowiggins le bourray sas",
    "drouin sa",
    "alpaci",
    "amcor tobacco packaging france sas",
    "burger & cie - maisons booa",
    "le nappage",
    "menuiserie charpente orvaltaise - mco",
    "poreaux et compagnie (groupe lapeyre)",
    "esdj escao associes",
    "papeteries de clairefontaine",
    "ateliers perrault frères",
    "mc france",
    "schmidt groupe",
    "cruard charpente et construction bois",
    "services onf nancy ( siège groupe ouest)",
    "méo (anciennement mc france)",
    "comec",
    "ds smith packaging france",
    "services onf epinal",
    "seyfert paper sas",
    "premdor magri",
    "macoretz bois",
    "egger panneaux & décors",
    "norske skog golbey",
    "novatissue sas",
    "kimberly-clark sas",
    "paul hartmann sa",
    "schilliger bois",
    "alsapan",
    "thevenin sarl",
    "georgia- pacific france",
    "huhtamaki la rochelle keyes emballages",
    "smurfit kappa bag in box",
    "sca packaging fegersheim",
    "ds smith",
    "menuiserie g. dubois",
    "papeteries des vosges",
    "burban palettes",
    "média 6.production bois",
    "uab union des artisans du bois",
    "wepa france",
    "cfs cellpack packaging",
    "ds smith paper kaysersberg",
    "unilin sas",
    "groupement des métiers du bois - gmb",
    "sca packaging nicollet",
    "munksjo stenay",
    "entreprise cordier",
    "delipapier",
    "smurfit kappa france",
    "rasec retail sas",
    "gpv france",
    "rossmann",
    "stal industrie sas",
    "essity operations france",
    "blue paper",
    "siat braun",
    "cuisine design industrie",
    "swiss krono sas",
    "menuiserie bieber",
    "onf",
    "steelcase sa",
    "wm 88",
    "munksjö arches",
    "seyfert champagne sas",
    "larivière",
    "services onf bar le duc raymond poincare",
    "k. line",
    "amcor flexibles sarrebourg sas",
    "minco sas"
]

lesjeudis_keywords = [
    "bases de données",
    "décisionnel",
    "datawarehouse",
    "erp",
    "progiciels",
    "crm",
    "etudes et développement",
    "energie",
    "hydraulique",
    "nucléaire",
    "pétrolier",
    "exploitation",
    "production",
    "internet",
    "intranet",
    "messagerie",
    "support",
    "bureautique",
    "helpdesk",
    "systèmes",
    "réseaux",
    "télécoms",
    "sécurité",
    "cao",
    "dao",
    "gpao",
    "conception et calcul de structures",
    "matériaux",
    "electronique",
    "carte à puces",
    "robotique",
    "etudes et développement",
    "energie",
    "hydraulique",
    "nucléaire",
    "pétrolier",
    "essais",
    "simulation",
    "test",
    "génie logiciel",
    "développement",
    "mécanique",
    "mécatronique",
    "méthode",
    "qualité",
    "process",
    "monétique",
    "optique",
    "optronique",
    "téléphonie",
    "radiocoms",
    "temps réel",
    "systèmes embarqués",
    "ingénieur d'affaires",
    "commercial",
    "conseil",
    "maîtrise d’ouvrage",
    "amo",
    "direction technique",
    "dsi"
]

last_posted = [
    u"Publié aujourd'hui",
    u"publié aujourd'hui",
    u"Publié il y a 1 jours",
    u"publié il y a 1 jours",
    u"Publié hier",
    u"publié hier",
    u"postée hier",
    u"postée il y a 1 heure",
    u"postée il y a 2 heures",
    u"postée il y a 3 heures",
    u"postée il y a 4 heures",
    u"postée il y a 5 heures",
    u"postée il y a 6 heures",
    u"postée il y a 7 heures",
    u"postée il y a 8 heures",
    u"postée il y a 9 heures",
    u"postée il y a 10 heures",
    u"postée il y a 11 heures",
    u"postée il y a 12 heures",
    u"postée il y a 13 heures",
    u"postée il y a 14 heures",
    u"postée il y a 15 heures",
    u"postée il y a 16 heures",
    u"postée il y a 17 heures",
    u"postée il y a 18 heures",
    u"postée il y a 19 heures",
    u"postée il y a 20 heures",
    u"postée il y a 21 heures",
    u"postée il y a 22 heures",
    u"postée il y a 23 heures",
    u"postée il y a 22 heures",
    u"il y a 1 jour",
    u"il y a 1 heure",
    u"il y a 2 heures",
    u"il y a 3 heures",
    u"il y a 4 heures",
    u"il y a 5 heures",
    u"il y a 6 heures",
    u"il y a 7 heures",
    u"il y a 8 heures",
    u"il y a 9 heures",
    u"il y a 10 heures",
    u"il y a 11 heures",
    u"il y a 12 heures",
    u"il y a 13 heures",
    u"il y a 14 heures",
    u"il y a 15 heures",
    u"il y a 16 heures",
    u"il y a 17 heures",
    u"il y a 18 heures",
    u"il y a 19 heures",
    u"il y a 20 heures",
    u"il y a 21 heures",
    u"il y a 22 heures",
    u"il y a 23 heures",
    u"il y a 22 heures",
    u"il y a 1 jour"
]

job_expired_messages = [
    u'The requested job vacancy was not found',
    u'was not found',
    u'n\'est plus en ligne',
    u'Cette page n\'existe pas ou plus',
    u'Désolé, cette offre est expirée',
    u'Désolé, nous ne pouvons pas trouver cette page',
    u'The job you asked for is not available'
]
