# -*- coding: utf-8 -*-

jobboards = ['indeed.fr',
                'ec.europa.eu',
                'optioncarriere',
                'pole-emploi.fr',
                'lesjeudis.com',
                'www.regionsjob.com',
                'keljob',
                'nostalentsnosemplois.auvergnerhonealpes.fr',
                'www.apec.fr',
                'meteojob',
                'cadremploi.fr',
                'glassdoor.fr',
                'monster.fr',
                'ec.europa.eu-api',
                'onf.fr',
                'lbmexecutivesearch',
                'lefigaro.fr'
                ]

occupations = [
    "tapissier d'ameublement",
    "charpentier bois poseur",
    "assistant developpement technique semences",
    "scieur bois",
    "monteur de charpentes bois",
    "monteur de meubles",
    "conducteur d'engins agricoles forestiers",
    "menuisier poseur agenceur",
    "charpentier",
    "ouvrier pepinieriste conditionnement",
    "stratifieur usineur finisseur",
    "ebeniste",
    "menuisier fabricant",
    "operateur de scierie",
    "geomaticien",
    "conducteur de broyeur",
    "ouvrier d'exploitation forestiere",
    "technicien ingenieur forestier",
    "conducteur de travaux forestiers",
    "dessinateur d'etudes batiments travaux publics",
    "operateur vernissage",
    "jardinier elagueur",
    "ouvrier pepiniere",
    "encadreur",
    "scieur de tete",
    "tourneur fraiseur",
    "aide menuisier",
    "conducteur d'engins forestiers",
    "technicien d'etudes batiments travaux publics",
    "technicien superieur ingenieur conseil de gestion forestiere travaux sylvicoles",
    "ingenieur forestier",
    "cartographe geomaticien",
    "monteur poseur agencement",
    "ouvrier paysagiste creation plantation",
    "pepinieriste viticole",
    "tourneur commande numerique cn",
    "menuisier agenceur de cuisines de salles de bains",
    "elagueur verts",
    "chef de projet agencement ebenisterie",
    "menuisier poseur de fermetures",
    "menuisier d'agencement",
    "architecte decorateur interieur concepteur espace de vie cuisines",
    "designer",
    "aide charpentier poseur",
    "vernisseur menuisier",
    "conducteur d'engins de debardage",
    "menuisier bois",
    "conducteur operateur de scierie",
    "menuisier ebeniste agenceur",
    "vernisseur laqueur",
    "peintre vernisseur",
    "ebeniste aeronautique",
    "menuisier poseur",
    "ouvrier ebeniste",
    "chef d'equipe elagueur grimpeur bucheron",
    "pilote de scie",
    "finisseur",
    "charpentier atelier",
    "approvisionneur",
    "dessinateur metreur",
    "conducteur de travaux elagage",
    "charpentier menuisier",
    "menuisier plaquiste",
    "pepinieriste",
    "peintre finisseur",
    "tapissier decorateur",
    "economiste de construction",
    "architecte d'interieur",
    "conducteur d ' engins forestiers",
    "tourneur",
    "agenceur d'interieur",
    "ouvrier paysagiste forestier",
    "tonnelier de fabrication",
    "architecte decorateur interieur concepteur espace de vie design",
    "approvisionneur logistique",
    "vernisseur bois",
    "geomaticien charge d'etudes sig",
    "menuisier charpentier",
    "technicien forestier",
    "vernisseur industriel",
    "technicien bureau d'etudes",
    "chauffeur super poids lourd grumier",
    "conducteur d'engins d'exploitation forestiere",
    "tourneur sur bois",
    "charge de projet amenagement territoire",
    "ouvrier forestier polyvalent",
    "menuisier agenceur ebeniste",
    "agent d'horticulture pepinieres oho",
    "metreur second oeuvre",
    "agent de fabrication tonnelier",
    "approvisionneur regional",
    "tonnelier menuisier",
    "projeteur bureau d'etudes",
    "preparateur de commande pepiniere",
    "technicien forestier territorial",
    "ouvrier sylviculteur",
    "ebeniste menuisier",
    "technicien forestier exploitation forestiere approvisionnement bois",
    "technico commercial deviseur",
    "assembleur monteur",
    "menuisier industrie bois",
    "dessinateur bureau d'etudes",
    "menuisier atelier bois",
    "charpentier bois",
    "agent pepinieriste",
    "monteur plv itinerant",
    "grimpeur elagueur",
    "commis de coupe",
    "menuisier",
    "menuisier bois metallier",
    "approvisionneur region",
    "ouvrier sylvicole",
    "technicien bureau d'etude charpente bois",
    "menuisier ebeniste",
    "chef d'equipe elagueur",
    "metreur verificateur",
    "tonnelier",
    "ouvrier paysagiste elagueur",
    "chef d'equipe de travaux forestiers",
    "conducteur d'abatteuses",
    "charge d'etude de prix metreur",
    "approvisionneur surface",
    "ingenieur des techniques forestieres",
    "conducteur de chargeuse porteur forestier",
    "menuisier d'atelier",
    "menuisier poseur atelier",
    "chef d'equipe de scierie",
    "menuisier installateur",
    "ouvrier pepinieriste",
    "aide pepinieriste",
    "sculpteur",
    "monteur",
    "bucheron",
    "menuisier operateur commande numerique",
    "bucheron elagueur",
    "metreur charpente menuiserie bois",
    "approvisionneur magasin",
    "ingenieur technicien forestier",
    "tonnelier reparateur",
    "deviseur",
    "paysagiste elagueur",
    "aide charpentier",
    "charpentier zingueur",
    "ouvrier forestier",
    "metreur",
    "metreur deviseur",
    "ouvrier bois",
    "chef d'equipe charpentier",
    "technicien forestier exploitation forestiere vente de bois",
    "agenceur",
    "acheteur",
    "charpentier poseur",
    "chauffeur grumier",
    "chef d'equipe elagueur bucheron",
    "ebeniste agenceur",
    "monteur agencement",
    "ouvrier de scierie",
    "monteur de maisons ossature bois",
    "elagueur grimpeur",
    "marqueteur",
    "menuisier agenceur",
    "conseiller forestier",
    "assistant de production pepiniere",
    "menuisier poseur agencement",
    "elagueur",
    "monteur de palettes",
    "agent pepinieriste oho",
    "ebeniste monteur meubles",
    "vernisseur",
    "architecte decorateur interieur concepteur espace de vie meubles",
    "parqueteur menuisier",
    "poseur de parquet",
    "ponceur vitrificateur",
    "sylviculteur",
    "mecanicien affuteur",
    "mecanicien d’entretien en exploitation forestiere",
    "constructeur bois",
    "responsable du parc a grumes",
    "responsable de parc a bois",
    "cariste",
    "magasinier",
    "manutentionnaire bois",
    "couvreur charpentier",
    "ingenieur papetier",
    "aide conducteur de machines a papier ou carton",
    "aide secheur en industrie papetiere",
    "Bobineur en industrie papetiere",
    "calandreur en industrie papetiere",
    "conducteur de ligne en industrie papetiere",
    "conducteur de machines a onduler",
    "enrouleur en industrie papetiere",
    "conducteur de machines d'impression",
    "imprimeur",
    "responsable commercial bois",
    "attache commercial bois",
    "technico commercial bois",
    "negociant en bois",
    "vendeur bois",
    "controleur de gestion",
    "comptable",
    "assistant ressources humaines",
    "peintre bois",
    "peinture bois"
]

lesjeudis_keywords = [
    "bases de données",
    "décisionnel",
    "datawarehouse",
    "erp",
    "progiciels",
    "crm",
    "etudes et développement",
    "energie",
    "hydraulique",
    "nucléaire",
    "pétrolier",
    "exploitation",
    "production",
    "internet",
    "intranet",
    "messagerie",
    "support",
    "bureautique",
    "helpdesk",
    "systèmes",
    "réseaux",
    "télécoms",
    "sécurité",
    "cao",
    "dao",
    "gpao",
    "conception et calcul de structures",
    "matériaux",
    "electronique",
    "carte à puces",
    "robotique",
    "etudes et développement",
    "energie",
    "hydraulique",
    "nucléaire",
    "pétrolier",
    "essais",
    "simulation",
    "test",
    "génie logiciel",
    "développement",
    "mécanique",
    "mécatronique",
    "méthode",
    "qualité",
    "process",
    "monétique",
    "optique",
    "optronique",
    "téléphonie",
    "radiocoms",
    "temps réel",
    "systèmes embarqués",
    "ingénieur d'affaires",
    "commercial",
    "conseil",
    "maîtrise d’ouvrage",
    "amo",
    "direction technique",
    "dsi"
]


