-- MySQL Script generated by MySQL Workbench
-- Fri Nov 19 16:46:03 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `product` ;

CREATE TABLE IF NOT EXISTS `product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `price` DECIMAL(10,2) NULL DEFAULT NULL,
  `is_in_stock` TINYINT(1) NULL DEFAULT NULL,
  `url` VARCHAR(255) NULL DEFAULT NULL,
  `url_review` VARCHAR(255) NULL DEFAULT NULL,
  `rating` FLOAT NULL DEFAULT NULL,
  `count_review` INT NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT now(),
  `product_id` VARCHAR(255) DEFAULT NULL,
  `rate` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dynamic_price`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dynamic_price` ;

CREATE TABLE IF NOT EXISTS `dynamic_price` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `price` DECIMAL(10,2) NULL DEFAULT NULL,
  `date` DATE NULL DEFAULT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `dr_idx` (`product_id` ASC) ,
  CONSTRAINT `dr`
    FOREIGN KEY (`product_id`)
    REFERENCES `product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `product_color`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `product_color` ;

CREATE TABLE IF NOT EXISTS `product_color` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hex` VARCHAR(255) NULL DEFAULT NULL,
  `product_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`, `product_id`),
  INDEX `pro_idx` (`product_id` ASC) ,
  CONSTRAINT `pro`
    FOREIGN KEY (`product_id`)
    REFERENCES `product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'таблица цветов продукта';


-- -----------------------------------------------------
-- Table `search_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `search_product` ;

CREATE TABLE IF NOT EXISTS `search_product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `child_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  INDEX `f_idx` (`product_id` ASC) ,
  INDEX `1_idx` (`child_id` ASC) ,
  CONSTRAINT `f`
    FOREIGN KEY (`product_id`)
    REFERENCES `product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `1`
    FOREIGN KEY (`child_id`)
    REFERENCES `product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `product_image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `product_image` ;

CREATE TABLE IF NOT EXISTS `product_image` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `path` TEXT NULL DEFAULT NULL,
  `type` ENUM('main', 'child') NULL DEFAULT NULL,
  `product_id` INT NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  INDEX `prod_idx` (`product_id` ASC) ,
  CONSTRAINT `prod2`
    FOREIGN KEY (`product_id`)
    REFERENCES `product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `product_price`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `product_price` ;

CREATE TABLE IF NOT EXISTS `product_price` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` TEXT NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `delivery` TEXT NULL DEFAULT NULL,
  `price` DECIMAL(10,2) NULL DEFAULT NULL,
  `product_id` INT NULL DEFAULT NULL,
  `count_review` INT NULL DEFAULT NULL,
  `rating` FLOAT NULL DEFAULT NULL,
  `discount_price` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `prod_idx` (`product_id` ASC) ,
  CONSTRAINT `prod`
    FOREIGN KEY (`product_id`)
    REFERENCES `product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `review` ;

CREATE TABLE IF NOT EXISTS `review` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `dignity` VARCHAR(255) NULL DEFAULT NULL,
  `flaw` VARCHAR(255) NULL DEFAULT NULL,
  `grade` INT NULL DEFAULT NULL,
  `product_id` INT NULL DEFAULT NULL,
  `date` DATE NULL DEFAULT NULL,
  `image` TEXT NULL DEFAULT NULL,
  `comment` TEXT NULL DEFAULT NULL,
  `use_experince` VARCHAR(255) NULL DEFAULT NULL,
  `city` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  INDEX `product_idx` (`product_id` ASC) ,
  CONSTRAINT `product55`
    FOREIGN KEY (`product_id`)
    REFERENCES `product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `category` ;

CREATE TABLE IF NOT EXISTS `category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `parent_id` INT NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `image_path` TEXT NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `category_search`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `category_search` ;

CREATE TABLE IF NOT EXISTS `category_search` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `child_id` INT NULL DEFAULT NULL,
  `category_id` INT NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  INDEX `category_idx` (`category_id` ASC) ,
  INDEX `category45_idx` (`child_id` ASC) ,
  CONSTRAINT `category3`
    FOREIGN KEY (`category_id`)
    REFERENCES `category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `category45`
    FOREIGN KEY (`child_id`)
    REFERENCES `category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `product_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `product_category` ;

CREATE TABLE IF NOT EXISTS `product_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NULL DEFAULT NULL,
  `category_id` INT NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  INDEX `prod_idx` (`product_id` ASC) ,
  INDEX `category_idx` (`category_id` ASC) ,
  CONSTRAINT `prod1`
    FOREIGN KEY (`product_id`)
    REFERENCES `product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `category`
    FOREIGN KEY (`category_id`)
    REFERENCES `category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tag` ;

CREATE TABLE IF NOT EXISTS `tag` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `category_id` INT NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  INDEX `fk_tag_category1_idx` (`category_id` ASC) ,
  CONSTRAINT `fk_tag_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `settings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `settings` ;

CREATE TABLE IF NOT EXISTS `settings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `settings_value`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `settings_value` ;

CREATE TABLE IF NOT EXISTS `settings_value` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `settings_id` INT NULL DEFAULT NULL,
  `value` TEXT NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  INDEX `settings_idx` (`settings_id` ASC) ,
  CONSTRAINT `settings4`
    FOREIGN KEY (`settings_id`)
    REFERENCES `settings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `product_settings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `product_settings` ;

CREATE TABLE IF NOT EXISTS `product_settings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NULL DEFAULT NULL,
  `settings_id` INT NULL DEFAULT NULL,
  `settings_value_id` INT NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  INDEX `product_idx` (`product_id` ASC) ,
  INDEX `settings_idx` (`settings_id` ASC) ,
  INDEX `value_idx` (`settings_value_Id` ASC) ,
  CONSTRAINT `product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `settings2`
    FOREIGN KEY (`settings_id`)
    REFERENCES `settings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `value`
    FOREIGN KEY (`settings_value_Id`)
    REFERENCES `settings_value` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `new_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `new_category` ;

CREATE TABLE IF NOT EXISTS `new_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NULL DEFAULT NULL,
  `new_category_id` INT NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  INDEX `category_idx` (`category_id` ASC) ,
  INDEX `new_idx` (`new_category_id` ASC) ,
  CONSTRAINT `category234`
    FOREIGN KEY (`category_id`)
    REFERENCES `category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `new`
    FOREIGN KEY (`new_category_id`)
    REFERENCES `category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `category_has_settings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `category_has_settings` ;

CREATE TABLE IF NOT EXISTS `category_has_settings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `settings_id` INT NULL DEFAULT NULL,
  `category_id` INT NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  INDEX `settings_idx` (`settings_id` ASC) ,
  INDEX `category_idx` (`category_id` ASC) ,
  CONSTRAINT `settings1`
    FOREIGN KEY (`settings_id`)
    REFERENCES `settings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `category34`
    FOREIGN KEY (`category_id`)
    REFERENCES `category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;